package com.bjwg.back.model;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_area_v2.area_id
     *
     * @mbggenerated
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_area_v2.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_area_v2.parent
     *
     * @mbggenerated
     */
    private Long parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_area_v2.zipcode
     *
     * @mbggenerated
     */
    private Integer zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_area_v2.baidu_code
     *
     * @mbggenerated
     */
    private Long baiduCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_area_v2.area_id
     *
     * @return the value of bjwg_area_v2.area_id
     *
     * @mbggenerated
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_area_v2.area_id
     *
     * @param areaId the value for bjwg_area_v2.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_area_v2.name
     *
     * @return the value of bjwg_area_v2.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_area_v2.name
     *
     * @param name the value for bjwg_area_v2.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_area_v2.parent
     *
     * @return the value of bjwg_area_v2.parent
     *
     * @mbggenerated
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_area_v2.parent
     *
     * @param parent the value for bjwg_area_v2.parent
     *
     * @mbggenerated
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_area_v2.zipcode
     *
     * @return the value of bjwg_area_v2.zipcode
     *
     * @mbggenerated
     */
    public Integer getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_area_v2.zipcode
     *
     * @param zipcode the value for bjwg_area_v2.zipcode
     *
     * @mbggenerated
     */
    public void setZipcode(Integer zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_area_v2.baidu_code
     *
     * @return the value of bjwg_area_v2.baidu_code
     *
     * @mbggenerated
     */
    public Long getBaiduCode() {
        return baiduCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_area_v2.baidu_code
     *
     * @param baiduCode the value for bjwg_area_v2.baidu_code
     *
     * @mbggenerated
     */
    public void setBaiduCode(Long baiduCode) {
        this.baiduCode = baiduCode;
    }
}