package com.bjwg.back.model;

import java.io.Serializable;

/**
 * 银行卡
 * @ClassName: BankCard 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-30 下午03:37:56
 */
public class BankCard implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3826862826728416728L;

	/**
     *
     * @mbggenerated
     */
    private Long cardId;

    /**
     * 卡号
     * @mbggenerated
     */
    private String cardNo;

    /**
     * 持卡人名称
     * @mbggenerated
     */
    private String accountName;

    /**
     * 卡类型 目前默认都是1
     * @mbggenerated
     */
    private Byte cardType;

    /**
     * 银行代号
     * @mbggenerated
     */
    private String bankCode;

    /**
     * 银行名称
     * @mbggenerated
     */
    private String bank;

    /**
     * 身份证号
     * @mbggenerated
     */
    private String idCard;

    /**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 联系电话
     * @mbggenerated
     */
    private String link;

    /**
     * 省份
     * @mbggenerated
     */
    private Long province;

    /**
     * 城市
     * @mbggenerated
     */
    private Long city;
    /**
     * 省份
     * @mbggenerated
     */
    private String provinceName;
    
    /**
     * 城市
     * @mbggenerated
     */
    private String cityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.card_id
     *
     * @return the value of bjwg_bank_card.card_id
     *
     * @mbggenerated
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.card_id
     *
     * @param cardId the value for bjwg_bank_card.card_id
     *
     * @mbggenerated
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.card_no
     *
     * @return the value of bjwg_bank_card.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.card_no
     *
     * @param cardNo the value for bjwg_bank_card.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.account_name
     *
     * @return the value of bjwg_bank_card.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.account_name
     *
     * @param accountName the value for bjwg_bank_card.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.card_type
     *
     * @return the value of bjwg_bank_card.card_type
     *
     * @mbggenerated
     */
    public Byte getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.card_type
     *
     * @param cardType the value for bjwg_bank_card.card_type
     *
     * @mbggenerated
     */
    public void setCardType(Byte cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.bank_code
     *
     * @return the value of bjwg_bank_card.bank_code
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.bank_code
     *
     * @param bankCode the value for bjwg_bank_card.bank_code
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.bank
     *
     * @return the value of bjwg_bank_card.bank
     *
     * @mbggenerated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.bank
     *
     * @param bank the value for bjwg_bank_card.bank
     *
     * @mbggenerated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.ID_card
     *
     * @return the value of bjwg_bank_card.ID_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.ID_card
     *
     * @param idCard the value for bjwg_bank_card.ID_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.user_id
     *
     * @return the value of bjwg_bank_card.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.user_id
     *
     * @param userId the value for bjwg_bank_card.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.link
     *
     * @return the value of bjwg_bank_card.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.link
     *
     * @param link the value for bjwg_bank_card.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.province
     *
     * @return the value of bjwg_bank_card.province
     *
     * @mbggenerated
     */
    public Long getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.province
     *
     * @param province the value for bjwg_bank_card.province
     *
     * @mbggenerated
     */
    public void setProvince(Long province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_bank_card.city
     *
     * @return the value of bjwg_bank_card.city
     *
     * @mbggenerated
     */
    public Long getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_bank_card.city
     *
     * @param city the value for bjwg_bank_card.city
     *
     * @mbggenerated
     */
    public void setCity(Long city) {
        this.city = city;
    }

	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}
}