package com.bjwg.back.model;

public class DictDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_dict_detail.dict_detail_id
     *
     * @mbggenerated
     */
    private Long dictDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_dict_detail.dict_id
     *
     * @mbggenerated
     */
    private Long dictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_dict_detail.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_dict_detail.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_dict_detail.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_dict_detail.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_dict_detail.dict_detail_id
     *
     * @return the value of bjwg_dict_detail.dict_detail_id
     *
     * @mbggenerated
     */
    public Long getDictDetailId() {
        return dictDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_dict_detail.dict_detail_id
     *
     * @param dictDetailId the value for bjwg_dict_detail.dict_detail_id
     *
     * @mbggenerated
     */
    public void setDictDetailId(Long dictDetailId) {
        this.dictDetailId = dictDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_dict_detail.dict_id
     *
     * @return the value of bjwg_dict_detail.dict_id
     *
     * @mbggenerated
     */
    public Long getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_dict_detail.dict_id
     *
     * @param dictId the value for bjwg_dict_detail.dict_id
     *
     * @mbggenerated
     */
    public void setDictId(Long dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_dict_detail.name
     *
     * @return the value of bjwg_dict_detail.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_dict_detail.name
     *
     * @param name the value for bjwg_dict_detail.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_dict_detail.code
     *
     * @return the value of bjwg_dict_detail.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_dict_detail.code
     *
     * @param code the value for bjwg_dict_detail.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_dict_detail.value
     *
     * @return the value of bjwg_dict_detail.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_dict_detail.value
     *
     * @param value the value for bjwg_dict_detail.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_dict_detail.remark
     *
     * @return the value of bjwg_dict_detail.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_dict_detail.remark
     *
     * @param remark the value for bjwg_dict_detail.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}