package com.bjwg.back.model;

import com.bjwg.back.base.Pages;
import com.bjwg.back.model.MyCouponExample.Criterion;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MyCouponUseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    protected Pages page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public MyCouponUseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public void setPage(Pages page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public Pages getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
        	condition = "1=1 "+condition;
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMyCouponUseIdIsNull() {
            addCriterion("t.my_coupon_use_id is null");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdIsNotNull() {
            addCriterion("t.my_coupon_use_id is not null");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdEqualTo(Long value) {
            addCriterion("t.my_coupon_use_id =", value, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdNotEqualTo(Long value) {
            addCriterion("t.my_coupon_use_id <>", value, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdGreaterThan(Long value) {
            addCriterion("t.my_coupon_use_id >", value, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("t.my_coupon_use_id >=", value, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdLessThan(Long value) {
            addCriterion("t.my_coupon_use_id <", value, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdLessThanOrEqualTo(Long value) {
            addCriterion("t.my_coupon_use_id <=", value, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdIn(List<Long> values) {
            addCriterion("t.my_coupon_use_id in", values, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdNotIn(List<Long> values) {
            addCriterion("t.my_coupon_use_id not in", values, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdBetween(Long value1, Long value2) {
            addCriterion("t.my_coupon_use_id between", value1, value2, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andMyCouponUseIdNotBetween(Long value1, Long value2) {
            addCriterion("t.my_coupon_use_id not between", value1, value2, "myCouponUseId");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNull() {
            addCriterion("t.coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNotNull() {
            addCriterion("t.coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouponIdEqualTo(Long value) {
            addCriterion("t.coupon_id =", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotEqualTo(Long value) {
            addCriterion("t.coupon_id <>", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThan(Long value) {
            addCriterion("t.coupon_id >", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThanOrEqualTo(Long value) {
            addCriterion("t.coupon_id >=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThan(Long value) {
            addCriterion("t.coupon_id <", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThanOrEqualTo(Long value) {
            addCriterion("t.coupon_id <=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdIn(List<Long> values) {
            addCriterion("t.coupon_id in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotIn(List<Long> values) {
            addCriterion("t.coupon_id not in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdBetween(Long value1, Long value2) {
            addCriterion("t.coupon_id between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotBetween(Long value1, Long value2) {
            addCriterion("t.coupon_id not between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponCodeIsNull() {
            addCriterion("t.coupon_code is null");
            return (Criteria) this;
        }

        public Criteria andCouponCodeIsNotNull() {
            addCriterion("t.coupon_code is not null");
            return (Criteria) this;
        }

        public Criteria andCouponCodeEqualTo(String value) {
            addCriterion("t.coupon_code =", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeNotEqualTo(String value) {
            addCriterion("t.coupon_code <>", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeGreaterThan(String value) {
            addCriterion("t.coupon_code >", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeGreaterThanOrEqualTo(String value) {
            addCriterion("t.coupon_code >=", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeLessThan(String value) {
            addCriterion("t.coupon_code <", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeLessThanOrEqualTo(String value) {
            addCriterion("t.coupon_code <=", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeLike(String value) {
            addCriterion("t.coupon_code like", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeNotLike(String value) {
            addCriterion("t.coupon_code not like", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeIn(List<String> values) {
            addCriterion("t.coupon_code in", values, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeNotIn(List<String> values) {
            addCriterion("t.coupon_code not in", values, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeBetween(String value1, String value2) {
            addCriterion("t.coupon_code between", value1, value2, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeNotBetween(String value1, String value2) {
            addCriterion("t.coupon_code not between", value1, value2, "couponCode");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("t.user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("t.user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("t.user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("t.user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("t.user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("t.user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("t.user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("t.user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("t.user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("t.user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("t.user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("t.user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUseTypeIsNull() {
            addCriterion("t.use_type is null");
            return (Criteria) this;
        }

        public Criteria andUseTypeIsNotNull() {
            addCriterion("t.use_type is not null");
            return (Criteria) this;
        }

        public Criteria andUseTypeEqualTo(Byte value) {
            addCriterion("t.use_type =", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotEqualTo(Byte value) {
            addCriterion("t.use_type <>", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeGreaterThan(Byte value) {
            addCriterion("t.use_type >", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("t.use_type >=", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLessThan(Byte value) {
            addCriterion("t.use_type <", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLessThanOrEqualTo(Byte value) {
            addCriterion("t.use_type <=", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeIn(List<Byte> values) {
            addCriterion("t.use_type in", values, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotIn(List<Byte> values) {
            addCriterion("t.use_type not in", values, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeBetween(Byte value1, Byte value2) {
            addCriterion("t.use_type between", value1, value2, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("t.use_type not between", value1, value2, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTimeIsNull() {
            addCriterion("t.use_time is null");
            return (Criteria) this;
        }

        public Criteria andUseTimeIsNotNull() {
            addCriterion("t.use_time is not null");
            return (Criteria) this;
        }

        public Criteria andUseTimeEqualTo(Date value) {
            addCriterion("t.use_time =", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeNotEqualTo(Date value) {
            addCriterion("t.use_time <>", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeGreaterThan(Date value) {
            addCriterion("t.use_time >", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("t.use_time >=", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeLessThan(Date value) {
            addCriterion("t.use_time <", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeLessThanOrEqualTo(Date value) {
            addCriterion("t.use_time <=", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeIn(List<Date> values) {
            addCriterion("t.use_time in", values, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeNotIn(List<Date> values) {
            addCriterion("t.use_time not in", values, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeBetween(Date value1, Date value2) {
            addCriterion("t.use_time between", value1, value2, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeNotBetween(Date value1, Date value2) {
            addCriterion("t.use_time not between", value1, value2, "useTime");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdIsNull() {
            addCriterion("t.my_coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdIsNotNull() {
            addCriterion("t.my_coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdEqualTo(Long value) {
            addCriterion("t.my_coupon_id =", value, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdNotEqualTo(Long value) {
            addCriterion("t.my_coupon_id <>", value, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdGreaterThan(Long value) {
            addCriterion("t.my_coupon_id >", value, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdGreaterThanOrEqualTo(Long value) {
            addCriterion("t.my_coupon_id >=", value, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdLessThan(Long value) {
            addCriterion("t.my_coupon_id <", value, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdLessThanOrEqualTo(Long value) {
            addCriterion("t.my_coupon_id <=", value, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdIn(List<Long> values) {
            addCriterion("t.my_coupon_id in", values, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdNotIn(List<Long> values) {
            addCriterion("t.my_coupon_id not in", values, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdBetween(Long value1, Long value2) {
            addCriterion("t.my_coupon_id between", value1, value2, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andMyCouponIdNotBetween(Long value1, Long value2) {
            addCriterion("t.my_coupon_id not between", value1, value2, "myCouponId");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyIsNull() {
            addCriterion("t.coupon_money is null");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyIsNotNull() {
            addCriterion("t.coupon_money is not null");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyEqualTo(BigDecimal value) {
            addCriterion("t.coupon_money =", value, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyNotEqualTo(BigDecimal value) {
            addCriterion("t.coupon_money <>", value, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyGreaterThan(BigDecimal value) {
            addCriterion("t.coupon_money >", value, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("t.coupon_money >=", value, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyLessThan(BigDecimal value) {
            addCriterion("t.coupon_money <", value, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("t.coupon_money <=", value, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyIn(List<BigDecimal> values) {
            addCriterion("t.coupon_money in", values, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyNotIn(List<BigDecimal> values) {
            addCriterion("t.coupon_money not in", values, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t.coupon_money between", value1, value2, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCouponMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t.coupon_money not between", value1, value2, "couponMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyIsNull() {
            addCriterion("t.can_use_money is null");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyIsNotNull() {
            addCriterion("t.can_use_money is not null");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyEqualTo(BigDecimal value) {
            addCriterion("t.can_use_money =", value, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyNotEqualTo(BigDecimal value) {
            addCriterion("t.can_use_money <>", value, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyGreaterThan(BigDecimal value) {
            addCriterion("t.can_use_money >", value, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("t.can_use_money >=", value, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyLessThan(BigDecimal value) {
            addCriterion("t.can_use_money <", value, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("t.can_use_money <=", value, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyIn(List<BigDecimal> values) {
            addCriterion("t.can_use_money in", values, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyNotIn(List<BigDecimal> values) {
            addCriterion("t.can_use_money not in", values, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t.can_use_money between", value1, value2, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andCanUseMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t.can_use_money not between", value1, value2, "canUseMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyIsNull() {
            addCriterion("t.use_money is null");
            return (Criteria) this;
        }

        public Criteria andUseMoneyIsNotNull() {
            addCriterion("t.use_money is not null");
            return (Criteria) this;
        }

        public Criteria andUseMoneyEqualTo(BigDecimal value) {
            addCriterion("t.use_money =", value, "useMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyNotEqualTo(BigDecimal value) {
            addCriterion("t.use_money <>", value, "useMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyGreaterThan(BigDecimal value) {
            addCriterion("t.use_money >", value, "useMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("t.use_money >=", value, "useMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyLessThan(BigDecimal value) {
            addCriterion("t.use_money <", value, "useMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("t.use_money <=", value, "useMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyIn(List<BigDecimal> values) {
            addCriterion("t.use_money in", values, "useMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyNotIn(List<BigDecimal> values) {
            addCriterion("t.use_money not in", values, "useMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t.use_money between", value1, value2, "useMoney");
            return (Criteria) this;
        }

        public Criteria andUseMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t.use_money not between", value1, value2, "useMoney");
            return (Criteria) this;
        }

        public Criteria andRelationIdIsNull() {
            addCriterion("t.relation_id is null");
            return (Criteria) this;
        }

        public Criteria andRelationIdIsNotNull() {
            addCriterion("t.relation_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelationIdEqualTo(Long value) {
            addCriterion("t.relation_id =", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotEqualTo(Long value) {
            addCriterion("t.relation_id <>", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThan(Long value) {
            addCriterion("t.relation_id >", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("t.relation_id >=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThan(Long value) {
            addCriterion("t.relation_id <", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThanOrEqualTo(Long value) {
            addCriterion("t.relation_id <=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdIn(List<Long> values) {
            addCriterion("t.relation_id in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotIn(List<Long> values) {
            addCriterion("t.relation_id not in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdBetween(Long value1, Long value2) {
            addCriterion("t.relation_id between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotBetween(Long value1, Long value2) {
            addCriterion("t.relation_id not between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andUseProvinceIsNull() {
            addCriterion("t.use_province is null");
            return (Criteria) this;
        }

        public Criteria andUseProvinceIsNotNull() {
            addCriterion("t.use_province is not null");
            return (Criteria) this;
        }

        public Criteria andUseProvinceEqualTo(Long value) {
            addCriterion("t.use_province =", value, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseProvinceNotEqualTo(Long value) {
            addCriterion("t.use_province <>", value, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseProvinceGreaterThan(Long value) {
            addCriterion("t.use_province >", value, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseProvinceGreaterThanOrEqualTo(Long value) {
            addCriterion("t.use_province >=", value, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseProvinceLessThan(Long value) {
            addCriterion("t.use_province <", value, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseProvinceLessThanOrEqualTo(Long value) {
            addCriterion("t.use_province <=", value, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseProvinceIn(List<Long> values) {
            addCriterion("t.use_province in", values, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseProvinceNotIn(List<Long> values) {
            addCriterion("t.use_province not in", values, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseProvinceBetween(Long value1, Long value2) {
            addCriterion("t.use_province between", value1, value2, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseProvinceNotBetween(Long value1, Long value2) {
            addCriterion("t.use_province not between", value1, value2, "useProvince");
            return (Criteria) this;
        }

        public Criteria andUseCityIsNull() {
            addCriterion("t.use_city is null");
            return (Criteria) this;
        }

        public Criteria andUseCityIsNotNull() {
            addCriterion("t.use_city is not null");
            return (Criteria) this;
        }

        public Criteria andUseCityEqualTo(Long value) {
            addCriterion("t.use_city =", value, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseCityNotEqualTo(Long value) {
            addCriterion("t.use_city <>", value, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseCityGreaterThan(Long value) {
            addCriterion("t.use_city >", value, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseCityGreaterThanOrEqualTo(Long value) {
            addCriterion("t.use_city >=", value, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseCityLessThan(Long value) {
            addCriterion("t.use_city <", value, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseCityLessThanOrEqualTo(Long value) {
            addCriterion("t.use_city <=", value, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseCityIn(List<Long> values) {
            addCriterion("t.use_city in", values, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseCityNotIn(List<Long> values) {
            addCriterion("t.use_city not in", values, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseCityBetween(Long value1, Long value2) {
            addCriterion("t.use_city between", value1, value2, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseCityNotBetween(Long value1, Long value2) {
            addCriterion("t.use_city not between", value1, value2, "useCity");
            return (Criteria) this;
        }

        public Criteria andUseAddressIsNull() {
            addCriterion("t.use_address is null");
            return (Criteria) this;
        }

        public Criteria andUseAddressIsNotNull() {
            addCriterion("t.use_address is not null");
            return (Criteria) this;
        }

        public Criteria andUseAddressEqualTo(String value) {
            addCriterion("t.use_address =", value, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressNotEqualTo(String value) {
            addCriterion("t.use_address <>", value, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressGreaterThan(String value) {
            addCriterion("t.use_address >", value, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressGreaterThanOrEqualTo(String value) {
            addCriterion("t.use_address >=", value, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressLessThan(String value) {
            addCriterion("t.use_address <", value, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressLessThanOrEqualTo(String value) {
            addCriterion("t.use_address <=", value, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressLike(String value) {
            addCriterion("t.use_address like", value, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressNotLike(String value) {
            addCriterion("t.use_address not like", value, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressIn(List<String> values) {
            addCriterion("t.use_address in", values, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressNotIn(List<String> values) {
            addCriterion("t.use_address not in", values, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressBetween(String value1, String value2) {
            addCriterion("t.use_address between", value1, value2, "useAddress");
            return (Criteria) this;
        }

        public Criteria andUseAddressNotBetween(String value1, String value2) {
            addCriterion("t.use_address not between", value1, value2, "useAddress");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("t.remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("t.remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("t.remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("t.remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("t.remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("t.remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("t.remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("t.remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("t.remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("t.remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("t.remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("t.remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("t.remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("t.remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}