package com.bjwg.back.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.bjwg.back.util.MyUtils;



/**
 * 我的收益/我参与的项目
 * @ClassName: MyEarnings 
 * @Description: TODO(这里用一句话描述这个类的作用) 
 * @author Administrator
 * @date 2015-9-15 上午11:20:57
 */
public class MyEarnings {
   

	/**
     *
     * @mbggenerated
     */
    private Long earningsId;

    /**
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 一期的抢购总数
     * @mbggenerated
     */
    private Integer num;

    /**
     * 年收益率
     * @mbggenerated
     */
    private BigDecimal rate;

    /**
     * 开始计时时间
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * 累计时间
     * @mbggenerated
     */
    private Integer days;

    /**
     * 截止计时时间
     * @mbggenerated
     */
    private Date endTime;

    /**
     * 成本价
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * 预期收益 = 成本 * 年收益率 * 累计时间 / 360 天
     * @mbggenerated
     */
    private BigDecimal expectEarning;

    /**
     * 抢购项目id
     * @mbggenerated
     */
    private Long paincbuyProjectId;

    /**
     * 抢购项目名称
     * @mbggenerated
     */
    private String paincbuyProjectName;

    /**
     * 赠书猪仔数量
     * @mbggenerated
     */
    private Integer presentNum;

    /**
     * 处理方式  1:委托寄卖2:屠宰配送3:领取活猪4:领取3000元／头的猪肉券
     * @mbggenerated
     */
    private Byte dealType;

    /**
     * 处理状态  0:未处理1:处理完成
     * @mbggenerated
     */
    private Byte dealStatus;

    /**
     * 处理时间
     * @mbggenerated
     */
    private Date dealTime;

    /**
     * 超期处理时间
     * @mbggenerated
     */
    private Date overTime;

    /**
     * 延期天数
     * @mbggenerated
     */
    private Integer overDays;

    /**
     * 备注
     * @mbggenerated
     */
    private String remark;

    /**
     * 变更前的处理方式
     * @mbggenerated
     */
    private Byte beforeDealType;
    
    
    /**
     * 自定义字段-- 总数
     */
    private Integer totalNum;
    /**
     * 自定义字段-- 抢购总数
     */
    private Integer purchaseNum;
    /**
     * 自定义字段-- 剩余数
     */
    private Integer leftNum;
    /**
     * 自定义字段-- 截止修改回报方式时间
     */
    private Date endModifyTime;
    /**
     * 自定义字段-- 格式化时间
     */
    private String fmtTime;
    /**
     * 自定义字段-- 间隔天数
     */
    private Long intervalDays;
    /**
     * 自定义字段-- 订单集合
     */
    private List<Order> orderList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.earnings_id
     *
     * @return the value of bjwg_my_earnings.earnings_id
     *
     * @mbggenerated
     */
    public Long getEarningsId() {
        return earningsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.earnings_id
     *
     * @param earningsId the value for bjwg_my_earnings.earnings_id
     *
     * @mbggenerated
     */
    public void setEarningsId(Long earningsId) {
        this.earningsId = earningsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.user_id
     *
     * @return the value of bjwg_my_earnings.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.user_id
     *
     * @param userId the value for bjwg_my_earnings.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.num
     *
     * @return the value of bjwg_my_earnings.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.num
     *
     * @param num the value for bjwg_my_earnings.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.rate
     *
     * @return the value of bjwg_my_earnings.rate
     *
     * @mbggenerated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.rate
     *
     * @param rate the value for bjwg_my_earnings.rate
     *
     * @mbggenerated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.begin_time
     *
     * @return the value of bjwg_my_earnings.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.begin_time
     *
     * @param beginTime the value for bjwg_my_earnings.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.days
     *
     * @return the value of bjwg_my_earnings.days
     *
     * @mbggenerated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.days
     *
     * @param days the value for bjwg_my_earnings.days
     *
     * @mbggenerated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.end_time
     *
     * @return the value of bjwg_my_earnings.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.end_time
     *
     * @param endTime the value for bjwg_my_earnings.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.money
     *
     * @return the value of bjwg_my_earnings.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.money
     *
     * @param money the value for bjwg_my_earnings.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.expect_earning
     *
     * @return the value of bjwg_my_earnings.expect_earning
     *
     * @mbggenerated
     */
    public BigDecimal getExpectEarning() {
        return expectEarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.expect_earning
     *
     * @param expectEarning the value for bjwg_my_earnings.expect_earning
     *
     * @mbggenerated
     */
    public void setExpectEarning(BigDecimal expectEarning) {
        this.expectEarning = expectEarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.paincbuy_project_id
     *
     * @return the value of bjwg_my_earnings.paincbuy_project_id
     *
     * @mbggenerated
     */
    public Long getPaincbuyProjectId() {
        return paincbuyProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.paincbuy_project_id
     *
     * @param paincbuyProjectId the value for bjwg_my_earnings.paincbuy_project_id
     *
     * @mbggenerated
     */
    public void setPaincbuyProjectId(Long paincbuyProjectId) {
        this.paincbuyProjectId = paincbuyProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.paincbuy_project_name
     *
     * @return the value of bjwg_my_earnings.paincbuy_project_name
     *
     * @mbggenerated
     */
    public String getPaincbuyProjectName() {
        return paincbuyProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.paincbuy_project_name
     *
     * @param paincbuyProjectName the value for bjwg_my_earnings.paincbuy_project_name
     *
     * @mbggenerated
     */
    public void setPaincbuyProjectName(String paincbuyProjectName) {
        this.paincbuyProjectName = paincbuyProjectName == null ? null : paincbuyProjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.present_num
     *
     * @return the value of bjwg_my_earnings.present_num
     *
     * @mbggenerated
     */
    public Integer getPresentNum() {
        return presentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.present_num
     *
     * @param presentNum the value for bjwg_my_earnings.present_num
     *
     * @mbggenerated
     */
    public void setPresentNum(Integer presentNum) {
        this.presentNum = presentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.deal_type
     *
     * @return the value of bjwg_my_earnings.deal_type
     *
     * @mbggenerated
     */
    public Byte getDealType() {
        return dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.deal_type
     *
     * @param dealType the value for bjwg_my_earnings.deal_type
     *
     * @mbggenerated
     */
    public void setDealType(Byte dealType) {
        this.dealType = dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.deal_status
     *
     * @return the value of bjwg_my_earnings.deal_status
     *
     * @mbggenerated
     */
    public Byte getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.deal_status
     *
     * @param dealStatus the value for bjwg_my_earnings.deal_status
     *
     * @mbggenerated
     */
    public void setDealStatus(Byte dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.deal_time
     *
     * @return the value of bjwg_my_earnings.deal_time
     *
     * @mbggenerated
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.deal_time
     *
     * @param dealTime the value for bjwg_my_earnings.deal_time
     *
     * @mbggenerated
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.over_time
     *
     * @return the value of bjwg_my_earnings.over_time
     *
     * @mbggenerated
     */
    public Date getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.over_time
     *
     * @param overTime the value for bjwg_my_earnings.over_time
     *
     * @mbggenerated
     */
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.over_days
     *
     * @return the value of bjwg_my_earnings.over_days
     *
     * @mbggenerated
     */
    public Integer getOverDays() {
        return overDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.over_days
     *
     * @param overDays the value for bjwg_my_earnings.over_days
     *
     * @mbggenerated
     */
    public void setOverDays(Integer overDays) {
        this.overDays = overDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.remark
     *
     * @return the value of bjwg_my_earnings.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.remark
     *
     * @param remark the value for bjwg_my_earnings.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_my_earnings.before_deal_type
     *
     * @return the value of bjwg_my_earnings.before_deal_type
     *
     * @mbggenerated
     */
    public Byte getBeforeDealType() {
        return beforeDealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_my_earnings.before_deal_type
     *
     * @param beforeDealType the value for bjwg_my_earnings.before_deal_type
     *
     * @mbggenerated
     */
    public void setBeforeDealType(Byte beforeDealType) {
        this.beforeDealType = beforeDealType;
    }

	public Integer getTotalNum() {
		return totalNum;
	}

	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}

	public Integer getPurchaseNum() {
		return purchaseNum;
	}

	public void setPurchaseNum(Integer purchaseNum) {
		this.purchaseNum = purchaseNum;
	}

	public Date getEndModifyTime() {
		return endModifyTime;
	}

	public void setEndModifyTime(Date endModifyTime) {
		this.endModifyTime = endModifyTime;
	}

	public String getFmtTime() {
		return fmtTime;
	}

	public void setFmtTime(String fmtTime) {
		this.fmtTime = fmtTime;
	}

	public Long getIntervalDays() {
		
		if(beginTime != null){
			
			Date date = new Date();
			
			intervalDays = MyUtils.calcDays(beginTime, date);
			
		}
		
		return intervalDays;
	}

	public void setIntervalDays(Long intervalDays) {
		this.intervalDays = intervalDays;
	}

	public Integer getLeftNum() {
		return leftNum;
	}

	public void setLeftNum(Integer leftNum) {
		this.leftNum = leftNum;
	}

	public List<Order> getOrderList() {
		return orderList;
	}

	public void setOrderList(List<Order> orderList) {
		this.orderList = orderList;
	}
}