package com.bjwg.back.model;

import java.math.BigDecimal;
import java.util.Date;

public class Pay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.trade_no
     *
     * @mbggenerated
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.trade_status
     *
     * @mbggenerated
     */
    private String tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.buyer
     *
     * @mbggenerated
     */
    private String buyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.seller
     *
     * @mbggenerated
     */
    private String seller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.gmt_create_time
     *
     * @mbggenerated
     */
    private Date gmtCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.gmt_pay_time
     *
     * @mbggenerated
     */
    private Date gmtPayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.total_money
     *
     * @mbggenerated
     */
    private BigDecimal totalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.fail_msg
     *
     * @mbggenerated
     */
    private String failMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.pay_type
     *
     * @mbggenerated
     */
    private Byte payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_pay.source_data
     *
     * @mbggenerated
     */
    private String sourceData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.trade_no
     *
     * @return the value of bjwg_pay.trade_no
     *
     * @mbggenerated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.trade_no
     *
     * @param tradeNo the value for bjwg_pay.trade_no
     *
     * @mbggenerated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.order_code
     *
     * @return the value of bjwg_pay.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.order_code
     *
     * @param orderCode the value for bjwg_pay.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.order_id
     *
     * @return the value of bjwg_pay.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.order_id
     *
     * @param orderId the value for bjwg_pay.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.trade_status
     *
     * @return the value of bjwg_pay.trade_status
     *
     * @mbggenerated
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.trade_status
     *
     * @param tradeStatus the value for bjwg_pay.trade_status
     *
     * @mbggenerated
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.buyer
     *
     * @return the value of bjwg_pay.buyer
     *
     * @mbggenerated
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.buyer
     *
     * @param buyer the value for bjwg_pay.buyer
     *
     * @mbggenerated
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.seller
     *
     * @return the value of bjwg_pay.seller
     *
     * @mbggenerated
     */
    public String getSeller() {
        return seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.seller
     *
     * @param seller the value for bjwg_pay.seller
     *
     * @mbggenerated
     */
    public void setSeller(String seller) {
        this.seller = seller == null ? null : seller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.gmt_create_time
     *
     * @return the value of bjwg_pay.gmt_create_time
     *
     * @mbggenerated
     */
    public Date getGmtCreateTime() {
        return gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.gmt_create_time
     *
     * @param gmtCreateTime the value for bjwg_pay.gmt_create_time
     *
     * @mbggenerated
     */
    public void setGmtCreateTime(Date gmtCreateTime) {
        this.gmtCreateTime = gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.gmt_pay_time
     *
     * @return the value of bjwg_pay.gmt_pay_time
     *
     * @mbggenerated
     */
    public Date getGmtPayTime() {
        return gmtPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.gmt_pay_time
     *
     * @param gmtPayTime the value for bjwg_pay.gmt_pay_time
     *
     * @mbggenerated
     */
    public void setGmtPayTime(Date gmtPayTime) {
        this.gmtPayTime = gmtPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.total_money
     *
     * @return the value of bjwg_pay.total_money
     *
     * @mbggenerated
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.total_money
     *
     * @param totalMoney the value for bjwg_pay.total_money
     *
     * @mbggenerated
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.fail_msg
     *
     * @return the value of bjwg_pay.fail_msg
     *
     * @mbggenerated
     */
    public String getFailMsg() {
        return failMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.fail_msg
     *
     * @param failMsg the value for bjwg_pay.fail_msg
     *
     * @mbggenerated
     */
    public void setFailMsg(String failMsg) {
        this.failMsg = failMsg == null ? null : failMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.pay_type
     *
     * @return the value of bjwg_pay.pay_type
     *
     * @mbggenerated
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.pay_type
     *
     * @param payType the value for bjwg_pay.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_pay.source_data
     *
     * @return the value of bjwg_pay.source_data
     *
     * @mbggenerated
     */
    public String getSourceData() {
        return sourceData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_pay.source_data
     *
     * @param sourceData the value for bjwg_pay.source_data
     *
     * @mbggenerated
     */
    public void setSourceData(String sourceData) {
        this.sourceData = sourceData == null ? null : sourceData.trim();
    }
}