package com.bjwg.back.model;

import java.util.Date;

public class Protocol {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_service_protocol.sp_id
     *
     * @mbggenerated
     */
    private Long spId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_service_protocol.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_service_protocol.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_service_protocol.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_service_protocol.sp_id
     *
     * @return the value of bjwg_service_protocol.sp_id
     *
     * @mbggenerated
     */
    public Long getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_service_protocol.sp_id
     *
     * @param spId the value for bjwg_service_protocol.sp_id
     *
     * @mbggenerated
     */
    public void setSpId(Long spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_service_protocol.ctime
     *
     * @return the value of bjwg_service_protocol.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_service_protocol.ctime
     *
     * @param ctime the value for bjwg_service_protocol.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_service_protocol.type
     *
     * @return the value of bjwg_service_protocol.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_service_protocol.type
     *
     * @param type the value for bjwg_service_protocol.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_service_protocol.content
     *
     * @return the value of bjwg_service_protocol.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_service_protocol.content
     *
     * @param content the value for bjwg_service_protocol.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
    
    public String title;

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
    
}