package com.bjwg.back.model;

public class Resc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_resc.resc_id
     *
     * @mbggenerated
     */
    private Long rescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_resc.resc_name
     *
     * @mbggenerated
     */
    private String rescName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_resc.resc_code
     *
     * @mbggenerated
     */
    private String rescCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_resc.resc_link
     *
     * @mbggenerated
     */
    private String rescLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_resc.security_code
     *
     * @mbggenerated
     */
    private String securityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_resc.resc_group
     *
     * @mbggenerated
     */
    private Long rescGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_resc.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_resc.resc_id
     *
     * @return the value of bjwg_resc.resc_id
     *
     * @mbggenerated
     */
    public Long getRescId() {
        return rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_resc.resc_id
     *
     * @param rescId the value for bjwg_resc.resc_id
     *
     * @mbggenerated
     */
    public void setRescId(Long rescId) {
        this.rescId = rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_resc.resc_name
     *
     * @return the value of bjwg_resc.resc_name
     *
     * @mbggenerated
     */
    public String getRescName() {
        return rescName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_resc.resc_name
     *
     * @param rescName the value for bjwg_resc.resc_name
     *
     * @mbggenerated
     */
    public void setRescName(String rescName) {
        this.rescName = rescName == null ? null : rescName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_resc.resc_code
     *
     * @return the value of bjwg_resc.resc_code
     *
     * @mbggenerated
     */
    public String getRescCode() {
        return rescCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_resc.resc_code
     *
     * @param rescCode the value for bjwg_resc.resc_code
     *
     * @mbggenerated
     */
    public void setRescCode(String rescCode) {
        this.rescCode = rescCode == null ? null : rescCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_resc.resc_link
     *
     * @return the value of bjwg_resc.resc_link
     *
     * @mbggenerated
     */
    public String getRescLink() {
        return rescLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_resc.resc_link
     *
     * @param rescLink the value for bjwg_resc.resc_link
     *
     * @mbggenerated
     */
    public void setRescLink(String rescLink) {
        this.rescLink = rescLink == null ? null : rescLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_resc.security_code
     *
     * @return the value of bjwg_resc.security_code
     *
     * @mbggenerated
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_resc.security_code
     *
     * @param securityCode the value for bjwg_resc.security_code
     *
     * @mbggenerated
     */
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode == null ? null : securityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_resc.resc_group
     *
     * @return the value of bjwg_resc.resc_group
     *
     * @mbggenerated
     */
    public Long getRescGroup() {
        return rescGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_resc.resc_group
     *
     * @param rescGroup the value for bjwg_resc.resc_group
     *
     * @mbggenerated
     */
    public void setRescGroup(Long rescGroup) {
        this.rescGroup = rescGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_resc.description
     *
     * @return the value of bjwg_resc.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_resc.description
     *
     * @param description the value for bjwg_resc.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}