package com.bjwg.back.model;

import com.bjwg.back.base.Pages;
import com.bjwg.back.model.OperationLogExample.Criterion;

import java.util.ArrayList;
import java.util.List;

public class RescExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    protected Pages page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public RescExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public void setPage(Pages page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public Pages getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
        	condition = "1=1 "+condition;
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRescIdIsNull() {
            addCriterion("resc.resc_id is null");
            return (Criteria) this;
        }

        public Criteria andRescIdIsNotNull() {
            addCriterion("resc.resc_id is not null");
            return (Criteria) this;
        }

        public Criteria andRescIdEqualTo(Long value) {
            addCriterion("resc.resc_id =", value, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescIdNotEqualTo(Long value) {
            addCriterion("resc.resc_id <>", value, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescIdGreaterThan(Long value) {
            addCriterion("resc.resc_id >", value, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescIdGreaterThanOrEqualTo(Long value) {
            addCriterion("resc.resc_id >=", value, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescIdLessThan(Long value) {
            addCriterion("resc.resc_id <", value, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescIdLessThanOrEqualTo(Long value) {
            addCriterion("resc.resc_id <=", value, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescIdIn(List<Long> values) {
            addCriterion("resc.resc_id in", values, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescIdNotIn(List<Long> values) {
            addCriterion("resc.resc_id not in", values, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescIdBetween(Long value1, Long value2) {
            addCriterion("resc.resc_id between", value1, value2, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescIdNotBetween(Long value1, Long value2) {
            addCriterion("resc.resc_id not between", value1, value2, "rescId");
            return (Criteria) this;
        }

        public Criteria andRescNameIsNull() {
            addCriterion("resc.resc_name is null");
            return (Criteria) this;
        }

        public Criteria andRescNameIsNotNull() {
            addCriterion("resc.resc_name is not null");
            return (Criteria) this;
        }

        public Criteria andRescNameEqualTo(String value) {
            addCriterion("resc.resc_name =", value, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameNotEqualTo(String value) {
            addCriterion("resc.resc_name <>", value, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameGreaterThan(String value) {
            addCriterion("resc.resc_name >", value, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameGreaterThanOrEqualTo(String value) {
            addCriterion("resc.resc_name >=", value, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameLessThan(String value) {
            addCriterion("resc.resc_name <", value, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameLessThanOrEqualTo(String value) {
            addCriterion("resc.resc_name <=", value, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameLike(String value) {
            addCriterion("resc.resc_name like", value, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameNotLike(String value) {
            addCriterion("resc.resc_name not like", value, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameIn(List<String> values) {
            addCriterion("resc.resc_name in", values, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameNotIn(List<String> values) {
            addCriterion("resc.resc_name not in", values, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameBetween(String value1, String value2) {
            addCriterion("resc.resc_name between", value1, value2, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescNameNotBetween(String value1, String value2) {
            addCriterion("resc.resc_name not between", value1, value2, "rescName");
            return (Criteria) this;
        }

        public Criteria andRescCodeIsNull() {
            addCriterion("resc.resc_code is null");
            return (Criteria) this;
        }

        public Criteria andRescCodeIsNotNull() {
            addCriterion("resc.resc_code is not null");
            return (Criteria) this;
        }

        public Criteria andRescCodeEqualTo(String value) {
            addCriterion("resc.resc_code =", value, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeNotEqualTo(String value) {
            addCriterion("resc.resc_code <>", value, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeGreaterThan(String value) {
            addCriterion("resc.resc_code >", value, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeGreaterThanOrEqualTo(String value) {
            addCriterion("resc.resc_code >=", value, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeLessThan(String value) {
            addCriterion("resc.resc_code <", value, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeLessThanOrEqualTo(String value) {
            addCriterion("resc.resc_code <=", value, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeLike(String value) {
            addCriterion("resc.resc_code like", value, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeNotLike(String value) {
            addCriterion("resc.resc_code not like", value, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeIn(List<String> values) {
            addCriterion("resc.resc_code in", values, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeNotIn(List<String> values) {
            addCriterion("resc.resc_code not in", values, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeBetween(String value1, String value2) {
            addCriterion("resc.resc_code between", value1, value2, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescCodeNotBetween(String value1, String value2) {
            addCriterion("resc.resc_code not between", value1, value2, "rescCode");
            return (Criteria) this;
        }

        public Criteria andRescLinkIsNull() {
            addCriterion("resc.resc_link is null");
            return (Criteria) this;
        }

        public Criteria andRescLinkIsNotNull() {
            addCriterion("resc.resc_link is not null");
            return (Criteria) this;
        }

        public Criteria andRescLinkEqualTo(String value) {
            addCriterion("resc.resc_link =", value, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkNotEqualTo(String value) {
            addCriterion("resc.resc_link <>", value, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkGreaterThan(String value) {
            addCriterion("resc.resc_link >", value, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkGreaterThanOrEqualTo(String value) {
            addCriterion("resc.resc_link >=", value, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkLessThan(String value) {
            addCriterion("resc.resc_link <", value, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkLessThanOrEqualTo(String value) {
            addCriterion("resc.resc_link <=", value, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkLike(String value) {
            addCriterion("resc.resc_link like", value, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkNotLike(String value) {
            addCriterion("resc.resc_link not like", value, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkIn(List<String> values) {
            addCriterion("resc.resc_link in", values, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkNotIn(List<String> values) {
            addCriterion("resc.resc_link not in", values, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkBetween(String value1, String value2) {
            addCriterion("resc.resc_link between", value1, value2, "rescLink");
            return (Criteria) this;
        }

        public Criteria andRescLinkNotBetween(String value1, String value2) {
            addCriterion("resc.resc_link not between", value1, value2, "rescLink");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeIsNull() {
            addCriterion("resc.security_code is null");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeIsNotNull() {
            addCriterion("resc.security_code is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeEqualTo(String value) {
            addCriterion("resc.security_code =", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotEqualTo(String value) {
            addCriterion("resc.security_code <>", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeGreaterThan(String value) {
            addCriterion("resc.security_code >", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("resc.security_code >=", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeLessThan(String value) {
            addCriterion("resc.security_code <", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeLessThanOrEqualTo(String value) {
            addCriterion("resc.security_code <=", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeLike(String value) {
            addCriterion("resc.security_code like", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotLike(String value) {
            addCriterion("resc.security_code not like", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeIn(List<String> values) {
            addCriterion("resc.security_code in", values, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotIn(List<String> values) {
            addCriterion("resc.security_code not in", values, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeBetween(String value1, String value2) {
            addCriterion("resc.security_code between", value1, value2, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotBetween(String value1, String value2) {
            addCriterion("resc.security_code not between", value1, value2, "securityCode");
            return (Criteria) this;
        }

        public Criteria andRescGroupIsNull() {
            addCriterion("resc.resc_group is null");
            return (Criteria) this;
        }

        public Criteria andRescGroupIsNotNull() {
            addCriterion("resc.resc_group is not null");
            return (Criteria) this;
        }

        public Criteria andRescGroupEqualTo(Long value) {
            addCriterion("resc.resc_group =", value, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andRescGroupNotEqualTo(Long value) {
            addCriterion("resc.resc_group <>", value, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andRescGroupGreaterThan(Long value) {
            addCriterion("resc.resc_group >", value, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andRescGroupGreaterThanOrEqualTo(Long value) {
            addCriterion("resc.resc_group >=", value, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andRescGroupLessThan(Long value) {
            addCriterion("resc.resc_group <", value, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andRescGroupLessThanOrEqualTo(Long value) {
            addCriterion("resc.resc_group <=", value, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andRescGroupIn(List<Long> values) {
            addCriterion("resc.resc_group in", values, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andRescGroupNotIn(List<Long> values) {
            addCriterion("resc.resc_group not in", values, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andRescGroupBetween(Long value1, Long value2) {
            addCriterion("resc.resc_group between", value1, value2, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andRescGroupNotBetween(Long value1, Long value2) {
            addCriterion("resc.resc_group not between", value1, value2, "rescGroup");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("resc.description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("resc.description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("resc.description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("resc.description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("resc.description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("resc.description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("resc.description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("resc.description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("resc.description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("resc.description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("resc.description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("resc.description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("resc.description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("resc.description not between", value1, value2, "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bjwg_resc
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bjwg_resc
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}