package com.bjwg.back.model;

public class Slide {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_slide.slide_id
     *
     * @mbggenerated
     */
    private Long slideId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_slide.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_slide.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_slide.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_slide.sort
     *
     * @mbggenerated
     */
    private Long sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_slide.slide_id
     *
     * @return the value of bjwg_slide.slide_id
     *
     * @mbggenerated
     */
    public Long getSlideId() {
        return slideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_slide.slide_id
     *
     * @param slideId the value for bjwg_slide.slide_id
     *
     * @mbggenerated
     */
    public void setSlideId(Long slideId) {
        this.slideId = slideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_slide.name
     *
     * @return the value of bjwg_slide.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_slide.name
     *
     * @param name the value for bjwg_slide.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_slide.path
     *
     * @return the value of bjwg_slide.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_slide.path
     *
     * @param path the value for bjwg_slide.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_slide.link
     *
     * @return the value of bjwg_slide.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_slide.link
     *
     * @param link the value for bjwg_slide.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_slide.sort
     *
     * @return the value of bjwg_slide.sort
     *
     * @mbggenerated
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_slide.sort
     *
     * @param sort the value for bjwg_slide.sort
     *
     * @mbggenerated
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }
}