package com.bjwg.back.model;

import java.util.Date;

public class UserPreorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_user_preorder.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_user_preorder.project_id
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_user_preorder.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_user_preorder.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_preorder.user_id
     *
     * @return the value of bjwg_user_preorder.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_preorder.user_id
     *
     * @param userId the value for bjwg_user_preorder.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_preorder.project_id
     *
     * @return the value of bjwg_user_preorder.project_id
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_preorder.project_id
     *
     * @param projectId the value for bjwg_user_preorder.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_preorder.ctime
     *
     * @return the value of bjwg_user_preorder.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_preorder.ctime
     *
     * @param ctime the value for bjwg_user_preorder.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_user_preorder.num
     *
     * @return the value of bjwg_user_preorder.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_user_preorder.num
     *
     * @param num the value for bjwg_user_preorder.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
    
    private String username;

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
    
}