package com.bjwg.back.model;

import java.math.BigDecimal;

public class Wallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet.wallet_id
     *
     * @mbggenerated
     */
    private Long walletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet.pay_password
     *
     * @mbggenerated
     */
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet.json
     *
     * @mbggenerated
     */
    private String json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet.wallet_id
     *
     * @return the value of bjwg_wallet.wallet_id
     *
     * @mbggenerated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet.wallet_id
     *
     * @param walletId the value for bjwg_wallet.wallet_id
     *
     * @mbggenerated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet.user_id
     *
     * @return the value of bjwg_wallet.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet.user_id
     *
     * @param userId the value for bjwg_wallet.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet.money
     *
     * @return the value of bjwg_wallet.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet.money
     *
     * @param money the value for bjwg_wallet.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet.status
     *
     * @return the value of bjwg_wallet.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet.status
     *
     * @param status the value for bjwg_wallet.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet.pay_password
     *
     * @return the value of bjwg_wallet.pay_password
     *
     * @mbggenerated
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet.pay_password
     *
     * @param payPassword the value for bjwg_wallet.pay_password
     *
     * @mbggenerated
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet.json
     *
     * @return the value of bjwg_wallet.json
     *
     * @mbggenerated
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet.json
     *
     * @param json the value for bjwg_wallet.json
     *
     * @mbggenerated
     */
    public void setJson(String json) {
        this.json = json == null ? null : json.trim();
    }
    
    /**
     * 用户名称
     */
    private String username;

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
}