package com.bjwg.back.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @author Administrator
 *
 */
public class WalletChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.wallet_change_id
     *
     * @mbggenerated
     */
    private Long walletChangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.wallet_id
     *
     * @mbggenerated
     */
    private Long walletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.before_money
     *
     * @mbggenerated
     */
    private BigDecimal beforeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.change_money
     *
     * @mbggenerated
     */
    private BigDecimal changeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.after_money
     *
     * @mbggenerated
     */
    private BigDecimal afterMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.change_type
     *
     * @mbggenerated
     */
    private Byte changeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.change_time
     *
     * @mbggenerated
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.relation_id
     *
     * @mbggenerated
     */
    private Long relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bjwg_wallet_change.relation_type
     *
     * @mbggenerated
     */
    private Byte relationType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.wallet_change_id
     *
     * @return the value of bjwg_wallet_change.wallet_change_id
     *
     * @mbggenerated
     */
    public Long getWalletChangeId() {
        return walletChangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.wallet_change_id
     *
     * @param walletChangeId the value for bjwg_wallet_change.wallet_change_id
     *
     * @mbggenerated
     */
    public void setWalletChangeId(Long walletChangeId) {
        this.walletChangeId = walletChangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.wallet_id
     *
     * @return the value of bjwg_wallet_change.wallet_id
     *
     * @mbggenerated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.wallet_id
     *
     * @param walletId the value for bjwg_wallet_change.wallet_id
     *
     * @mbggenerated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.user_id
     *
     * @return the value of bjwg_wallet_change.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.user_id
     *
     * @param userId the value for bjwg_wallet_change.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.before_money
     *
     * @return the value of bjwg_wallet_change.before_money
     *
     * @mbggenerated
     */
    public BigDecimal getBeforeMoney() {
        return beforeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.before_money
     *
     * @param beforeMoney the value for bjwg_wallet_change.before_money
     *
     * @mbggenerated
     */
    public void setBeforeMoney(BigDecimal beforeMoney) {
        this.beforeMoney = beforeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.change_money
     *
     * @return the value of bjwg_wallet_change.change_money
     *
     * @mbggenerated
     */
    public BigDecimal getChangeMoney() {
        return changeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.change_money
     *
     * @param changeMoney the value for bjwg_wallet_change.change_money
     *
     * @mbggenerated
     */
    public void setChangeMoney(BigDecimal changeMoney) {
        this.changeMoney = changeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.after_money
     *
     * @return the value of bjwg_wallet_change.after_money
     *
     * @mbggenerated
     */
    public BigDecimal getAfterMoney() {
        return afterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.after_money
     *
     * @param afterMoney the value for bjwg_wallet_change.after_money
     *
     * @mbggenerated
     */
    public void setAfterMoney(BigDecimal afterMoney) {
        this.afterMoney = afterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.change_type
     *
     * @return the value of bjwg_wallet_change.change_type
     *
     * @mbggenerated
     */
    public Byte getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.change_type
     *
     * @param changeType the value for bjwg_wallet_change.change_type
     *
     * @mbggenerated
     */
    public void setChangeType(Byte changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.change_time
     *
     * @return the value of bjwg_wallet_change.change_time
     *
     * @mbggenerated
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.change_time
     *
     * @param changeTime the value for bjwg_wallet_change.change_time
     *
     * @mbggenerated
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.relation_id
     *
     * @return the value of bjwg_wallet_change.relation_id
     *
     * @mbggenerated
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.relation_id
     *
     * @param relationId the value for bjwg_wallet_change.relation_id
     *
     * @mbggenerated
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bjwg_wallet_change.relation_type
     *
     * @return the value of bjwg_wallet_change.relation_type
     *
     * @mbggenerated
     */
    public Byte getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bjwg_wallet_change.relation_type
     *
     * @param relationType the value for bjwg_wallet_change.relation_type
     *
     * @mbggenerated
     */
    public void setRelationType(Byte relationType) {
        this.relationType = relationType;
    }
    
    private String username;

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
    
}