package com.bjwg.back.dao;

import com.bjwg.back.model.MyCouponUse;
import com.bjwg.back.model.MyCouponUseExample;
import java.util.List;

public interface MyCouponUseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    int countByExample(MyCouponUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long myCouponUseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    int insert(MyCouponUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    int insertSelective(MyCouponUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    List<MyCouponUse> selectByExample(MyCouponUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    MyCouponUse selectByPrimaryKey(Long myCouponUseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MyCouponUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon_use
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MyCouponUse record);
}