package com.bjwg.back.dao;

import com.bjwg.back.model.MyCoupon;
import com.bjwg.back.model.MyCouponExample;
import java.util.List;

public interface MyCouponDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int countByExample(MyCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long myCouponId);
    /**
     * 通过用户id批量删除用户猪肉券记录
     * @param userIds
     * @return
     */
    int deleteByUserIds(List<Long> userIds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int insert(MyCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int insertSelective(MyCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    List<MyCoupon> selectByExample(MyCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    MyCoupon selectByPrimaryKey(Long myCouponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MyCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_my_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MyCoupon record);
    
    /**
     * 批量增加数据
     * @param record
     * @return
     */
    int insertBatch (List<MyCoupon> records);
}