package com.bjwg.back.dao;

import com.bjwg.back.model.OperationLog;
import com.bjwg.back.model.OperationLogExample;
import java.util.List;

public interface OperationLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_operation_log
     *
     * @mbggenerated
     */
    int countByExample(OperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_operation_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long opeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_operation_log
     *
     * @mbggenerated
     */
    int insert(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_operation_log
     *
     * @mbggenerated
     */
    int insertSelective(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_operation_log
     *
     * @mbggenerated
     */
    List<OperationLog> selectByExample(OperationLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_operation_log
     *
     * @mbggenerated
     */
    OperationLog selectByPrimaryKey(Long opeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_operation_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_operation_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperationLog record);
}