package com.bjwg.back.dao;

import com.bjwg.back.model.Protocol;
import com.bjwg.back.model.ProtocolExample;
import java.util.List;

public interface ProtocolDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int countByExample(ProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int insert(Protocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int insertSelective(Protocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    List<Protocol> selectByExampleWithBLOBs(ProtocolExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    List<Protocol> selectByExample(ProtocolExample example);
    
    /**
     * 得到所有的协议
     * @param example
     * @return
     */
    List<Protocol> getAll(ProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    Protocol selectByPrimaryKey(Long spId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Protocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Protocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_service_protocol
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Protocol record);
}