package com.bjwg.back.dao;

import com.bjwg.back.model.Slide;
import com.bjwg.back.model.SlideExample;
import java.util.List;

public interface SlideDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_slide
     *
     * @mbggenerated
     */
    int countByExample(SlideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_slide
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long slideId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_slide
     *
     * @mbggenerated
     */
    int insert(Slide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_slide
     *
     * @mbggenerated
     */
    int insertSelective(Slide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_slide
     *
     * @mbggenerated
     */
    List<Slide> selectByExample(SlideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_slide
     *
     * @mbggenerated
     */
    Slide selectByPrimaryKey(Long slideId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_slide
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Slide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_slide
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Slide record);
}