package com.bjwg.back.dao;

import com.bjwg.back.model.WalletChange;
import com.bjwg.back.model.WalletChangeExample;
import java.util.List;

public interface WalletChangeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_wallet_change
     *
     * @mbggenerated
     */
    int countByExample(WalletChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_wallet_change
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long walletChangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_wallet_change
     *
     * @mbggenerated
     */
    int insert(WalletChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_wallet_change
     *
     * @mbggenerated
     */
    int insertSelective(WalletChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_wallet_change
     *
     * @mbggenerated
     */
    List<WalletChange> selectByExample(WalletChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_wallet_change
     *
     * @mbggenerated
     */
    WalletChange selectByPrimaryKey(Long walletChangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_wallet_change
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WalletChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_wallet_change
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WalletChange record);
    /**
     * 批量插入余额变更信息
     * @param list
     * @return
     */
    int insertBatch(List<WalletChange> list);
}