package com.bjwg.back.dao;

import com.bjwg.back.model.Withdraw;
import com.bjwg.back.model.WithdrawExample;
import com.bjwg.back.vo.HomeView;

import java.util.List;

public interface WithdrawDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int countByExample(WithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long withwradalsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int insert(Withdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int insertSelective(Withdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    List<Withdraw> selectByExample(WithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    Withdraw selectByPrimaryKey(Long withwradalsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Withdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bjwg_withdrawals
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Withdraw record);
    
    HomeView selectWithdrawCount(WithdrawExample example);
}